### ISSUE TITLE
Create REST User API

### ISSUE THREAD

**Issue by nataliemeurer** [germTheory/germTheoryWebApp#11]
We expose the following REST endpoints:
- GET /api/users
- GET /api/users/:user_id
- POST /api/users/
- GET /api/locations
- GET /api/locations/:location_id
- POST /api/locations/

cc: @kmeurer, @rstellar, @jjmerino, @jamesongamble, @suprbh

**Comment by ryojiosawa** [comment]
@kmeurer, @suprbh, @jjmerino, @jamesongamble - please have a look at the list of REST endpoints we should support for User and Location.  Once we confirm that this is what we want to implement, we should first write tests for these endpoints.

**Comment by jjmerino** [comment]
the three endpoints for locations are implemented with tests now. @suprbh close it if you are done too! :)
