### ISSUE TITLE
Create Architecture Diagram

### ISSUE THREAD

**Issue by ryojiosawa** [germTheory/germTheoryWebApp#17]

**Comment by ryojiosawa** [comment]
@germTheory/hr-contributors - here are some of our sequence diagrams:

Mobile User -> Server -> DB
![image](https://cloud.githubusercontent.com/assets/862544/4910991/da192872-6486-11e4-9ae7-4d07591953c2.png)

Admin -> Web -> Server -> Background Job -> DB
![image](https://cloud.githubusercontent.com/assets/862544/4910974/a39d604c-6486-11e4-8442-9d966867fa13.png)

**Comment by jamesongamble** [comment]
![img_7103](https://cloud.githubusercontent.com/assets/7300285/4911014/482a7ece-6487-11e4-83d5-e92ee9ec1ee2.JPG)
