### ISSUE TITLE
Restructure server file to better accomodate Sequelize

### ISSUE THREAD

**Issue by nataliemeurer** [germTheory/germTheoryWebApp#76]
Proposed server structure:
/server
    /configs
         serverConfig.js
   /models
         db.js -- this includes schema definition and model methods
    /controllers
        UserController.js
        LocationController.js
   /routes
        UserRoutes.js
        LocationRoutes.js
  /public
  /views
       --view templates should be here
/specs
    /server
    /mobile

**Comment by ryojiosawa** [comment]
@kmeurer, @jjmerino, @jamesongamble, @suprbh - please have a look at the new directory structure we're currently considering.  If you have any concerns or questions, please let us know asap.
